// src/components/NFTGenerator.tsx
import { useState } from 'react';
import Replicate from 'replicate-js'; // Or Hugging Face API

const replicate = new Replicate({ auth: process.env.REPLICATE_API_TOKEN });

export function NFTGenerator({ onGenerated }: { onGenerated: (uri: string) => void }) {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError('Please enter a description for your NFT.');
      return;
    }

    setLoading(true);
    setError(null);
    try {
      // AI image generation (Instamint pattern) with improved error handling
      const output = await replicate.run("stability-ai/stable-diffusion:ac732df83cea7fff18b8472768c88ad041fa750ff7682a21affe81863cbe77e4", {
        input: { prompt },
      });

      if (!output || !output[0]) {
        throw new Error('No image generated. Please try a different prompt.');
      }

      const imageUrl = output[0]; // Assume first output is image URL

      // Upload metadata to IPFS with validation
      const metadata = { 
        name: 'AI-Generated NFT', 
        description: prompt, 
        image: imageUrl,
        attributes: [{ trait_type: 'Generated By', value: 'AI Instamint' }] // Added for richer metadata
      };
      
      const response = await fetch('/api/ai/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(metadata),
      });

      if (!response.ok) {
        throw new Error('IPFS upload failed. Please try again.');
      }

      const { ipfsUri } = await response.json();
      onGenerated(ipfsUri); // Pass to parent (e.g., listing form)
    } catch (error) {
      console.error(error);
      setError(error instanceof Error ? error.message : 'An unknown error occurred during generation.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ marginBottom: '1rem' }}>
      <input 
        value={prompt} 
        onChange={(e) => setPrompt(e.target.value)} 
        placeholder="Describe your NFT (e.g., 'A futuristic cityscape at sunset')" 
        style={{ width: '100%', padding: '0.5rem', marginBottom: '0.5rem' }}
        disabled={loading}
      />
      <button 
        onClick={handleGenerate} 
        disabled={loading}
        style={{ 
          padding: '0.5rem 1rem', 
          background: loading ? '#ccc' : '#4a90d9', 
          color: 'white', 
          border: 'none', 
          cursor: loading ? 'not-allowed' : 'pointer' 
        }}
      >
        {loading ? 'Generating...' : 'Generate AI NFT'}
      </button>
      {error && <p style={{ color: 'red', marginTop: '0.5rem' }}>{error}</p>}
    </div>
  );
}
