'use client';
import { useState } from 'react';

export function NFTGenerator({ onGenerated }: { onGenerated: (uri: string) => void }) {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError('Please enter a description for your NFT.');
      return;
    }

    setLoading(true);
    setError(null);
    try {
      // Call backend API to generate image
      const genResponse = await fetch('/api/ai/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      if (!genResponse.ok) {
        throw new Error('Image generation failed. Please try again.');
      }

      const { imageUrl } = await genResponse.json();

      // Upload metadata to IPFS
      const metadata = { 
        name: 'AI-Generated NFT', 
        description: prompt, 
        image: imageUrl,
        attributes: [{ trait_type: 'Generated By', value: 'AI Instamint' }]
      };
      
      const response = await fetch('/api/ai/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(metadata),
      });

      if (!response.ok) {
        throw new Error('IPFS upload failed. Please try again.');
      }

      const { ipfsUri } = await response.json();
      onGenerated(ipfsUri);
    } catch (error) {
      console.error(error);
      setError(error instanceof Error ? error.message : 'An unknown error occurred during generation.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ marginBottom: '1rem' }}>
      <input 
        value={prompt} 
        onChange={(e) => setPrompt(e.target.value)} 
        placeholder="Describe your NFT (e.g., 'A futuristic cityscape at sunset')" 
        style={{ width: '100%', padding: '0.5rem', marginBottom: '0.5rem' }}
        disabled={loading}
      />
      <button 
        onClick={handleGenerate} 
        disabled={loading}
        style={{ 
          padding: '0.5rem 1rem', 
          background: loading ? '#ccc' : '#4a90d9', 
          color: 'white', 
          border: 'none', 
          cursor: loading ? 'not-allowed' : 'pointer' 
        }}
      >
        {loading ? 'Generating...' : 'Generate AI NFT'}
      </button>
      {error && <p style={{ color: 'red', marginTop: '0.5rem' }}>{error}</p>}
    </div>
  );
}
